/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domen.AvioKompanijaPartner;
import domen.Mesto;
import dto.ServerTransferObjekat;
import java.util.*;
import javax.swing.*;
import kontroler.Kontroler;
import java.text.*;
import util.Util;
/**
 *
 * @author Nevena
 */
public class UnosAvioKompanija extends javax.swing.JDialog {

    /**
     * Creates new form UnosAvioKompanija
     */
    public UnosAvioKompanija(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        popuniComboMesta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfSifraAvk = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtfNazivAvk = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jtfZiroRn = new javax.swing.JTextField();
        jtfMejl = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtfTelefon = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jcbMesto = new javax.swing.JComboBox();
        jtfUlica = new javax.swing.JTextField();
        jtfBroj = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jtfDatum = new javax.swing.JTextField();
        jbtnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Sifra");

        jLabel2.setText("Naziv");

        jLabel3.setText("Ziro racun");

        jLabel4.setText("Email");

        jLabel6.setText("Telefon");

        jLabel7.setText("Mesto");

        jLabel8.setText("Ulica");

        jLabel9.setText("Broj");

        jcbMesto.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(41, 41, 41)
                        .addComponent(jcbMesto, 0, 212, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfBroj)
                            .addComponent(jtfUlica))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jcbMesto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtfUlica, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtfBroj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel10.setText("Datum partnerstva");

        jtfDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfDatumActionPerformed(evt);
            }
        });

        jbtnSacuvaj.setText("Sacuvaj");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jbtnSacuvaj)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(25, 25, 25)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel6)
                                .addComponent(jLabel10))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jtfSifraAvk)
                                .addComponent(jtfNazivAvk)
                                .addComponent(jtfZiroRn, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(jtfMejl, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(jtfTelefon, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
                                .addComponent(jtfDatum)))))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfSifraAvk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfNazivAvk, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfZiroRn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfMejl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jtfDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jbtnSacuvaj)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        // TODO add your handling code here:
        int odluka = JOptionPane.showConfirmDialog(this, "Da li zelite da sacuvate ovog partnera?");
        if (odluka == JOptionPane.YES_OPTION) {
            String sSifra = jtfSifraAvk.getText().trim();
            String naziv = jtfNazivAvk.getText().trim();
            String ziro = jtfZiroRn.getText().trim();
            String sDatum = jtfDatum.getText().trim();
            String telefon = jtfTelefon.getText().trim();
            String email = jtfMejl.getText().trim();
            String ulica = jtfUlica.getText().trim();
            String broj = jtfBroj.getText().trim();
            Mesto mesto = (Mesto) jcbMesto.getSelectedItem();
            try {
                AvioKompanijaPartner partner = kreirajPartnera(sSifra, naziv, ziro, sDatum, telefon, email, ulica, broj, mesto);
                Kontroler.getInstance().unesiPartneraUBazu(partner);
                ServerTransferObjekat sto = (ServerTransferObjekat) Kontroler.getInstance().getMapa().get("sacuvanPartner");
                if (sto.getStatus() == Util.SERVER_STATUS_OPERACIJA_OK) {
                    JOptionPane.showMessageDialog(this, sto.getRezultat().toString());
                } else {
                    JOptionPane.showMessageDialog(this, sto.getGreska());
                }
               // JOptionPane.showMessageDialog(this, "Partner je sacuvan u bazi!!!");
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }

    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    private void jtfDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfDatumActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfDatumActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JComboBox jcbMesto;
    private javax.swing.JTextField jtfBroj;
    private javax.swing.JTextField jtfDatum;
    private javax.swing.JTextField jtfMejl;
    private javax.swing.JTextField jtfNazivAvk;
    private javax.swing.JTextField jtfSifraAvk;
    private javax.swing.JTextField jtfTelefon;
    private javax.swing.JTextField jtfUlica;
    private javax.swing.JTextField jtfZiroRn;
    // End of variables declaration//GEN-END:variables

    private void popuniComboMesta() {
        try {
            List<Mesto> mesta = Kontroler.getInstance().vratiListuMesta();
            jcbMesto.setModel(new DefaultComboBoxModel(mesta.toArray()));
            Date dat = new Date();
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
            String datum = sdf.format(dat);
            jtfDatum.setText(datum);
            jtfDatum.setEditable(false);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, ex.getMessage());
        }

    }

    private AvioKompanijaPartner kreirajPartnera(String sSifra, String naziv, String ziro, String sDatum, String telefon, String email, String ulica, String broj, Mesto mesto) throws Exception {
        AvioKompanijaPartner partner = new AvioKompanijaPartner();

        if (sSifra == null || sSifra.isEmpty()) {
            throw new Exception("Sifra nije uneta!!!");
        }
        try {
            int sifra = Integer.parseInt(sSifra);
            partner.setSifraAVK(sifra);
        } catch (Exception e) {
            throw new Exception("Sifru treba uneti u numerickom formatu!!!");
        }
        if (naziv == null || naziv.isEmpty()) {
            throw new Exception("Naziv kompanije nije unet!!!");
        }
        partner.setNaziv(naziv);
        if (ziro == null || ziro.isEmpty()) {
            throw new Exception("Ziro-racun kompanije nije unet!!!");
        }
        if (ziro.length() != 18) {
            throw new Exception("Ziro-racun kompanije nije unet u odgovarajucem formatu!!!");
        }
        partner.setZiroRacun(ziro);
        if (sDatum == null || sDatum.isEmpty()) {
            throw new Exception("Datum sklapanja partnerstva sa kompanijom nije unet!!!");
        }
        try {
            SimpleDateFormat sdf = new SimpleDateFormat("dd.MM.yyyy.");
            Date dat = sdf.parse(sDatum);
            partner.setDatumSklapanjaPartnerstva(dat);
        } catch (Exception e) {
            throw new Exception("Datum sklapanja partnerstva sa kompanijom nije unet u odgovarajucem formatu!!!");
        }
        if (telefon == null || telefon.isEmpty()) {
            throw new Exception("Telefon kompanije nije unet!!!");
        }
        partner.setTelefon(telefon);
        if (email == null || email.isEmpty()) {
            throw new Exception("E-mail adresa kompanije nije uneta!!!");
        }
//        if (!email.contains("@")) {
//            throw new Exception("E-mail adresa kompanije nije uneta u odgovarajucem formatu!!!");
//        }
        partner.setEmail(email);
        if (ulica == null || ulica.isEmpty()) {
            throw new Exception("Ulica u kojoj se nalazi kompanija nije uneta!!!");
        }
        partner.setUlica(ulica);
        if (broj == null || broj.isEmpty()) {
            throw new Exception("Broj u ulici u kojoj se nalazi kompanija nije unet!!!");
        }
        partner.setBroj(broj);
        partner.setMesto(mesto);
        return partner;
    }

}
