/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import domen.Let;
import domen.Putnik;
import dto.ServerTransferObjekat;
import javax.swing.JOptionPane;
import kontroler.Kontroler;
import util.Util;

/**
 *
 * @author Nevena
 */
public class UnosPutnika extends javax.swing.JDialog {

    /**
     * Creates new form UnosPutnika
     */
    UnosLetova unos;
    public UnosPutnika(java.awt.Frame parent, boolean modal, UnosLetova unos) {
        super(parent, modal);
        initComponents();
        this.unos = unos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtfBrojPasosa = new javax.swing.JTextField();
        jtfIme = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtfPrezime = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtfJMBG = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtfMejl = new javax.swing.JTextField();
        jtfTelefon = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jbtnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Broj pasosa");

        jLabel2.setText("Ime");

        jLabel3.setText("Prezime");

        jLabel4.setText("JMBG");

        jLabel5.setText("E-mail");

        jLabel6.setText("Telefon");

        jbtnSacuvaj.setText("Sacuvaj");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addComponent(jtfBrojPasosa, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfIme, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jtfMejl, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfJMBG, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfPrezime, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbtnSacuvaj, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtfTelefon, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE))))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtfBrojPasosa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtfIme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jtfPrezime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtfJMBG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jtfMejl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtfTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jbtnSacuvaj)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        // TODO add your handling code here:
        int odluka = JOptionPane.showConfirmDialog(this, "Da li zelite da sacuvate ovog putnika?");
        if (odluka == JOptionPane.YES_OPTION) {
            try {
                Putnik putnik = kreirajPutnika();
                Kontroler.getInstance().sacuvajPutnika(putnik);
                ServerTransferObjekat sto = (ServerTransferObjekat) Kontroler.getInstance().getMapa().get("sacuvanPutnik");
                if (sto.getStatus() == Util.SERVER_STATUS_OPERACIJA_OK) {
                    JOptionPane.showMessageDialog(this, sto.getRezultat().toString());
                    unos.popuniComboPutnici();
                } else {
                    JOptionPane.showMessageDialog(this, sto.getGreska());
                }
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(this, ex.getMessage());
            }
        }
        
        
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JTextField jtfBrojPasosa;
    private javax.swing.JTextField jtfIme;
    private javax.swing.JTextField jtfJMBG;
    private javax.swing.JTextField jtfMejl;
    private javax.swing.JTextField jtfPrezime;
    private javax.swing.JTextField jtfTelefon;
    // End of variables declaration//GEN-END:variables

    private Putnik kreirajPutnika() throws Exception {
        Putnik p = new Putnik();
        String pasos = jtfBrojPasosa.getText().trim();
        if (pasos == null || pasos.isEmpty()) {
            throw new Exception("Niste uneli broj pasosa!!!");
        }
        if (pasos.length() != 9) {
            throw new Exception("Broj pasosa mora imati 9 cifara!!!");
        }
        for (int i = 0; i < pasos.length(); i++) {
            char broj = pasos.charAt(i);
            if (!Character.isDigit(broj)) {
                throw new Exception("Broj pasosa uneti u odgovarajucem formatu!!!");
            }
        }
        p.setBrojPasosa(pasos);
        String ime = jtfIme.getText().trim();
        if (ime == null || ime.isEmpty()) {
            throw new Exception("Niste uneli ime osobe!!!");
        }
        p.setIme(ime);        
        String prezime = jtfPrezime.getText().trim();
        if (prezime== null || prezime.isEmpty()) {
            throw new Exception("Niste uneli prezime osobe!!!");
        }
        p.setPrezime(prezime);
        String jmbg = jtfJMBG.getText().trim();
        if (jmbg == null || jmbg.isEmpty()) {
            throw new Exception("Niste uneli maticni broj osobe!!!");
        }
        if (jmbg.length() != 13) {
            throw new Exception("Maticni broj mora imati 13 cifara!!!");
        }
        for (int i = 0; i < jmbg.length(); i++) {
            char broj = jmbg.charAt(i);
            if (!Character.isDigit(broj)) {
                throw new Exception("Maticni broj uneti u odgovarajucem formatu!!!");
            }
        }
        p.setJmbg(jmbg);
        String mejl = jtfMejl.getText().trim();
        if (mejl == null || mejl.isEmpty()) {
            throw new Exception("Niste uneli e-mail adresu osobe!!!");
        }
        if (!mejl.contains("@")) {
            throw new Exception("Uneti e-mail osobe u odgovarajucem formatu!!!");
        }
        char prvi = mejl.charAt(0);
        if (prvi == '@') {
            throw new Exception("Uneti e-mail osobe u odgovarajucem formatu!!!");
        }
        char poslednji = mejl.charAt(mejl.length()-1);
        if (poslednji == '@') {
            throw new Exception("Uneti e-mail osobe u odgovarajucem formatu!!!");
        }
        p.setEmail(mejl);
        String fon = jtfTelefon.getText().trim();
        if (fon == null || fon.isEmpty()) {
            throw new Exception("Niste uneli broj telefona osobe!!!");
        }
        for (int i = 0; i < fon.length(); i++) {
            char broj = fon.charAt(i);
            if (!Character.isDigit(broj)) {
                throw new Exception("Telefon osobe uneti u odgovarajucem formatu!!!");
            }
        }
        p.setTelefon(fon);
        return p;
    }
}
