/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package gui;

import db.DBKonekcija;
import db.ParametriBaze;
import java.io.File;
import java.io.FileOutputStream;
import java.io.OutputStream;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import kontroler.Kontroler;

/**
 *
 * @author Nevena
 */
public class ParametriBazeGUI extends javax.swing.JDialog {

    /**
     * Creates new form ParametriBaze
     */
    public ParametriBazeGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        prikazi();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jcbTipBaze = new javax.swing.JComboBox();
        jpnlParametriBaze = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlblBaza = new javax.swing.JLabel();
        jtxtUsername = new javax.swing.JTextField();
        jpfPassword = new javax.swing.JPasswordField();
        jtxtNazivBaze = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jtxtPort = new javax.swing.JTextField();
        jbtnTest = new javax.swing.JButton();
        jbtnSacuvaj = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Tip baze:");

        jcbTipBaze.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "MySQL", "SQL Server", "Oracle" }));

        jpnlParametriBaze.setBorder(javax.swing.BorderFactory.createTitledBorder("Parametri baze:"));

        jLabel2.setText("Username:");

        jLabel3.setText("Password:");

        jlblBaza.setText("Naziv baze:");

        jLabel4.setText("Port:");

        javax.swing.GroupLayout jpnlParametriBazeLayout = new javax.swing.GroupLayout(jpnlParametriBaze);
        jpnlParametriBaze.setLayout(jpnlParametriBazeLayout);
        jpnlParametriBazeLayout.setHorizontalGroup(
            jpnlParametriBazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlParametriBazeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlParametriBazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jlblBaza)
                    .addComponent(jLabel4))
                .addGap(24, 24, 24)
                .addGroup(jpnlParametriBazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtUsername)
                    .addComponent(jpfPassword)
                    .addComponent(jtxtNazivBaze)
                    .addComponent(jtxtPort, javax.swing.GroupLayout.DEFAULT_SIZE, 253, Short.MAX_VALUE))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        jpnlParametriBazeLayout.setVerticalGroup(
            jpnlParametriBazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnlParametriBazeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnlParametriBazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jtxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnlParametriBazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jpfPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnlParametriBazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblBaza)
                    .addComponent(jtxtNazivBaze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jpnlParametriBazeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jtxtPort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jbtnTest.setText("Testiraj konekciju");
        jbtnTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnTestActionPerformed(evt);
            }
        });

        jbtnSacuvaj.setText("Sacuvaj");
        jbtnSacuvaj.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSacuvajActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(76, 76, 76)
                        .addComponent(jcbTipBaze, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addComponent(jbtnTest)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbtnSacuvaj))
                        .addComponent(jpnlParametriBaze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jcbTipBaze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jpnlParametriBaze, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtnSacuvaj)
                    .addComponent(jbtnTest))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtnTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnTestActionPerformed
        try {
            String tipBaze = (String) jcbTipBaze.getSelectedItem();
            String username = jtxtUsername.getText().trim();
            char[] cp = jpfPassword.getPassword();
            String pass = "";
            for (char p : cp) {
                pass += p;
            }
            String nazivBaze = jtxtNazivBaze.getText().trim();
            int port = Integer.parseInt(jtxtPort.getText().trim());
            DBKonekcija.testirajKonekciju(tipBaze, username, pass, nazivBaze, port);
            JOptionPane.showMessageDialog(this, "Uspesna konekcija");
        } catch (Exception ex) {
            Logger.getLogger(ParametriBazeGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnTestActionPerformed

    private void jbtnSacuvajActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSacuvajActionPerformed
        String tipBaze = (String) jcbTipBaze.getSelectedItem();
        String username = jtxtUsername.getText().trim();
        char[] cp = jpfPassword.getPassword();
        String pass = "";
        for (char p : cp) {
            pass += p;
        }
        String nazivBaze = jtxtNazivBaze.getText().trim();
        int port = Integer.parseInt(jtxtPort.getText().trim());
        try {
            DBKonekcija.testirajKonekciju(tipBaze, username, pass, nazivBaze, port);
            save(tipBaze, username, pass, nazivBaze, port);
            JOptionPane.showMessageDialog(this, "Sacuvano");
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(ParametriBazeGUI.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, ex.getMessage(), "Greska", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_jbtnSacuvajActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JButton jbtnSacuvaj;
    private javax.swing.JButton jbtnTest;
    private javax.swing.JComboBox jcbTipBaze;
    private javax.swing.JLabel jlblBaza;
    private javax.swing.JPasswordField jpfPassword;
    private javax.swing.JPanel jpnlParametriBaze;
    private javax.swing.JTextField jtxtNazivBaze;
    private javax.swing.JTextField jtxtPort;
    private javax.swing.JTextField jtxtUsername;
    // End of variables declaration//GEN-END:variables

    private void save(String tipBaze, String username, String pass, String nazivBaze, int port) throws Exception {
        try {
            Properties prop = new Properties();
            prop.setProperty(Kontroler.TIP_BAZE, tipBaze);
            prop.setProperty(Kontroler.USERNAME, username);
            prop.setProperty(Kontroler.PASSWORD, pass);
            prop.setProperty(Kontroler.NAZIV_BAZE, nazivBaze);
            prop.setProperty(Kontroler.PORT, String.valueOf(port));
            File f = new File("db.properties");
            OutputStream out = new FileOutputStream(f);
            prop.store(out, "");
        } catch (Exception e) {
            throw new Exception("Greska tokom cuvanja parameatara baze: " + e.getMessage());
        }
    }

    private void prikazi() {
        ParametriBaze pb = Kontroler.getInstance().dajParametre();

        jtxtNazivBaze.setText(pb.getBaza());
        jtxtUsername.setText(pb.getUsername());
        jpfPassword.setText(pb.getPass());
        jcbTipBaze.setSelectedItem(pb.getTipBaze());
        jtxtPort.setText(pb.getPort() + "");
    }
}
